server:
  port: 8082

spring:
  application:
    name: todo-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: todo-service
      auto-index-creation: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

# Thêm cấu hình JWT giống user-service
jwt:
  secret: ThisIsAReallyLongAndSecureSecretKeyForJWTEncodingDecodingPleaseChangeThis
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 